Bugfix: Throw if user was created without a license
memgraph/memgraph pull request #1067
Opened 2023-07-07 11:09 UTC by andrejtonev

[master < Task] PR
- [ ] Check, and update documentation if necessary
- [ ] Provide the full content or a guide for the final git message

To keep docs changelog up to date, one more thing to do:
- [ ] Write a release note here, including added/changed clauses
- [ ] Tag someone from docs team in the comments

De-serializing the user/role will throw if the user/role was created without a valid license, but is being read with a valid license.
To fix this, we just default construct the fine_grained_access_handler and read from it if a valid one is found in the auth db.

@kgolubic

2023-07-27 04:45 UTC, as51340 requested changes

2023-07-27 04:45 UTC, as51340 commented on src/auth/models.cpp
>      return {data["username"], data["password_hash"], permissions, fine_grained_access_handler};
```suggestion
    return {data["username"], data["password_hash"], permissions, std::move(fine_grained_access_handler)};
```

2023-08-01 07:19 UTC, as51340 approved these changes

2023-08-01 21:36 UTC, merged

2023-08-02 07:39 UTC, vpavicic commented
@andrejtonev - a release note please :)

2023-08-02 09:26 UTC, andrejtonev commented
@vpavicic 

Users created with the Community Edition caused an exception when read with the Enterprise Edition. This was due missing information that was not saved in the Community Edition, but was checked for in the Enterprise Edition.

2023-08-02 10:51 UTC, vpavicic commented
@andrejtonev can I use the release note i wrote above? The point is that now all the users you create in the community edition will remain when you upgrade to the  enterprise edition

2023-08-02 11:25 UTC, andrejtonev commented
@vpavicic 
Remain sounds like we used to delete them. They persisted, it's just that they didn't work.

Maybe:
Users created in the Community Edition remain valid after the instance is upgraded to an Enterprise Edition. The user's fine grained permission will default to none after the upgrade.

2023-08-03 08:20 UTC, vpavicic commented
I don't think fine-grained permissions can even be set in the community edition, you can only create a user with a password, that's it

2023-08-03 08:23 UTC, andrejtonev commented
Exactly, the fine grained permissions is the info missing that causes the failure after upgrading to Enterprise. Now, instead of throwing an error when the fine grained permissions are missing, we just default them to none and move on.

2023-08-03 08:34 UTC, vpavicic commented
Oh ok! I won't include that as I don't think users need that much info.. what's important here is that if you created users in the community, they will still be there when you upgrade :) thnx!