[master < TXXXX] Return cartesian product on multi match clauses
memgraph/memgraph pull request #1193
Opened 2023-08-23 16:52 UTC by Josipmrden

In multi match clauses, the result of 2 matches equals a cartesian product of rows. If both match clauses have filters, then there is a quadratic amount of filtering operations in the system.

[master < Task] PR
- [ ] Check, and update documentation if necessary
- [ ] Provide the full content or a guide for the final git message

2023-10-18 18:44 UTC, antepusic requested changes
Good job! I’ve left a few comments below:

2023-10-18 18:44 UTC, antepusic commented on src/query/plan/pretty_print.cpp
> +}
I suggest implementing `PlanPrinter::Previsit` for this operator with a `ToString` method, consistently with other operators that have detailed info (see [PR](https://github.com/memgraph/memgraph/pull/1204)).

2023-10-18 18:44 UTC, antepusic commented on tests/unit/query_plan.cpp
>  }
What’s the reason as to why only one branch of `IndexedJoin` contains `ScanAllByLabelPropertyValue`, whereas the other one does `ScanAllByLabel`?

2023-10-18 18:44 UTC, antepusic commented on src/query/plan/preprocess.cpp
> +              "Expansion expansion group ID is not assigned to the pattern!");
```suggestion
              "Expansion group ID is not assigned to the pattern!");
```

2023-10-19 09:48 UTC, antoniofilipovic requested changes
I checked PR and don't have many comments. Good work, left few suggestions otherwise it seems fine to me

2023-10-19 09:48 UTC, antoniofilipovic reviewed
I checked PR and don't have many comments. Good work, left few suggestions otherwise it seems fine to me

2023-10-23 20:09 UTC, antepusic requested changes
Having investigated, the checks are failing because `cartesian_product_enabled_` is turned off during unit test execution.

2023-10-24 12:12 UTC, antepusic reviewed
This looks good and very close to mergeable, and I’ve resolved some of my earlier comments. Before I hit approve, please respond to the remaining two comments I had left :smile:

2023-10-24 13:41 UTC, antepusic approved these changes
Everything looks good to me now, and the checks are now passing :rocket:

2023-10-24 13:41 UTC, antoniofilipovic approved these changes
Looks good to me

2023-10-24 19:54 UTC, merged