Add GQL behave tests for on-disk storage
memgraph/memgraph pull request #1238
Opened 2023-09-07 20:23 UTC by Darych

[master < Epic] PR
- [ ] Check, and update documentation if necessary
- [ ] Write E2E tests
- [ ] Compare the [benchmarking results](https://bench-graph.memgraph.com/) between the master branch and the Epic branch
- [ ] Provide the full content or a guide for the final git message

[master < Task] PR
- [ ] Check, and update documentation if necessary
- [ ] Provide the full content or a guide for the final git message

To keep docs changelog up to date, one more thing to do:
- [ ] Write a release note here, including added/changed clauses
- [ ] Tag someone from docs team in the comments

2023-09-25 06:01 UTC, Darych commented on src/query/db_accessor.hpp
> +    accessor_->PrefetchOutEdges(vertex_accessor->impl_);
The test which failed here now uses `DetachDelete` function.
But we still call this function in `mgp_graph_delete_vertex` without prefetching edges.
Also `DetachDelete` prefetches edges and call `accessor_->DetachDelete()` internally.
Here `accessor_->DeleteVertex()` calls `accessor_->DetachDelete` also.
So we must prefetch edges.

2023-09-26 12:16 UTC, as51340 requested changes

2023-09-26 12:16 UTC, as51340 commented on tests/gql_behave/run.sh
I don't think this file should exist. If you need it on pipeline, you can add it as part of the step there. e2e tests also need mgclient but we don't run it by explicitly installing mgclient. Check how e2e tests work :smile:

2023-09-26 12:16 UTC, as51340 commented on tests/gql_behave/run.py
> +    if parsed_args.storage_mode == "in_memory":
Add storage mode flag will be merged today -> no need to introduce setup queries, we can just start Memgraph with any storage mode.

2023-09-26 12:40 UTC, gvolfing commented on tests/gql_behave/run.sh
Second that.
If it's not a huge chunk of work.

2023-09-26 12:42 UTC, gvolfing reviewed
The existence of `run.sh` as @as51340 mentioned. If it's not a huge chunk of work I would rather not have this solved this way.

2023-09-26 19:06 UTC, Darych commented on tests/gql_behave/run.sh
I agree. But there are also in e2e tests:
```
# TODO(gitbuda): Setup mgclient and pymgclient properly.
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:../../libs/mgclient/lib
```

2023-10-03 19:57 UTC, Darych commented
In this PR I start to use `tests/ve3` for gql_behave tests. I will remove virtual env from gql_behave directory in separate PR, to not mess everything inside one.

2023-10-09 11:21 UTC, as51340 approved these changes

2023-10-09 11:21 UTC, as51340 commented on tests/setup.sh
> +        NEW_LD_LIBRARY_PATH=$NEW_LD_LIBRARY_PATH:"../libs/mgclient/lib"
```suggestion
        NEW_LD_LIBRARY_PATH=$LD_LIBRARY_PATH:"../libs/mgclient/lib"
```

2023-10-09 11:52 UTC, gvolfing approved these changes

2023-10-10 06:27 UTC, merged