[master < ] Fix a crash caused when declaring a path with only one node in OPTIONAL MATCH clause
memgraph/memgraph pull request #1318
Opened 2023-09-29 15:35 UTC by DavIvek

A query that defines path as just a single node that is already declared in the previous MATCH or OPTIONAL MATCH clause, for example, MATCH (n1) OPTIONAL MATCH p=(n1) RETURN 1; will fail and will crash memgraph.

When the user defines a path, memgraph will generate a ConstructNamedPath operator. Memgraph uses bound_symbols to save symbols for which it needs to generate a ScanAll operator. If the path has a relationship, memgraph will generate an Expand logical operator.
A case in which the path consists of only a single node and that node is already in bound_symbols isn't covered, so memgraph will fail in the planning phase.

[master < Task] PR
- [ ] Check, and update documentation if necessary
- [ ] Provide the full content or a guide for the final git message

To keep docs changelog up to date, one more thing to do:
- [ ] Write a release note here, including added/changed clauses
- [ ] Tag someone from docs team in the comments

closes #1293

2023-09-29 15:44 UTC, DavIvek commented
With these changes, memgraph will cover this case by generating Filter and ConstructNamedPath operators without ScanAll operator, since ScanAll is already applied because it's in bound_symbols.

2023-10-05 09:44 UTC, Ignition requested changes
Can you add a testcase.

Plus, there is a whole class of problem that would be great to fix while you are in this code. For example:

EXPLAIN MATCH (n2) OPTIONAL MATCH p=(n1)-[]->(n2)-[]->(n3) RETURN p;
+----------------------------------+
| QUERY PLAN                       |
+----------------------------------+
| " * Produce {p}"                 |
| " * Optional"                    |
| " |\\ "                          |
| " | * ConstructNamedPath"        |
| " | * EdgeUniquenessFilter"      |
| " | * Expand (n2)-[anon3]->(n3)" |
| " | * Expand (n1)-[anon2]->(n2)" |
| " | * ScanAll (n1)"              |
| " | * Once"                      |
| " * ScanAll (n2)"                |
| " * Once"                        |
+----------------------------------+

Would be better as 

+----------------------------------+
| QUERY PLAN                       |
+----------------------------------+
| " * Produce {p}"                 |
| " * Optional"                    |
| " |\\ "                          |
| " | * ConstructNamedPath"        |
| " | * EdgeUniquenessFilter"      |
| " | * Expand (n2)-[anon3]->(n3)" |
| " | * Expand (n2)<-[anon2]-(n1)" |
| " | * Once"                      |
| " * ScanAll (n2)"                |
| " * Once"                        |
+----------------------------------+

2023-10-05 16:08 UTC, DavIvek commented
Added a testcase to cover this case and opened an issue for possible optimization with a planner.

2023-10-09 12:17 UTC, Ignition approved these changes

2023-10-09 13:25 UTC, merged