[master < ] Fix order by memory spike bug
memgraph/memgraph pull request #1451
Opened 2023-11-03 17:25 UTC by mpintaric55334

[master < Epic] PR
- [ ] Check, and update documentation if necessary
- [ ] Write E2E tests
- [ ] Compare the [benchmarking results](https://bench-graph.memgraph.com/) between the master branch and the Epic branch
- [ ] Provide the full content or a guide for the final git message

[master < Task] PR
- [x] Check, and update documentation if necessary
- [x] Provide the full content or a guide for the final git message

Memory spike when using order by has been fixed.

Closes : https://github.com/memgraph/memgraph/issues/1170

To keep docs changelog up to date, one more thing to do:
- [ ] Write a release note here, including added/changed clauses
- [ ] Tag someone from docs team in the comments

2023-11-03 17:26 UTC, mpintaric55334 commented
This needs to be discussed, because it can make problems with other queries that use ORDER BY. cc @antoniofilipovic

2023-11-05 11:40 UTC, as51340 requested changes
Ping fico for reviewing this I am not relevant enough here. I checked Grafana worklads, nothing seems broken. However, we should add workloads for order by and then inspect what is going on. I can give you jump-start in mgbench tomorrow if you need some help

2023-11-05 11:40 UTC, as51340 commented on src/query/interpreter.cpp
> +      return isOrderBy;
```suggestion
      return !return_clause->body_.order_by.empty();
```

2023-11-07 10:27 UTC, antoniofilipovic commented
I would add workload here, just to be sure how will this behave later on.

2023-11-08 14:34 UTC, antepusic reviewed
Good work! I have no comments other than what Andi and FIćo have brought up already – just make sure to address them

2023-11-22 09:21 UTC, antoniofilipovic requested changes
I think workload needs to land on master first

2024-07-01 11:23 UTC, closed without merging

2024-07-01 11:23 UTC, imilinovic commented
I think we had some changes in monotonic memory usage so I think this isn't up to date anymore, closed for now.