SHOW DATABASES query improvement
memgraph/memgraph pull request #1547
Opened 2023-11-28 11:18 UTC by andrejtonev

`SHOW DATABASES` query returns a matrix with 2 columns: "Name", "Current".
Each row represents one database, with the "Current" being a simple flag (`*`) to show which database is currently the active one.

This is somewhat convoluted, especially when we just want to find our current database among many other databases.

This PR simplifies this by introducing a new query `SHOW DATABASE` which returns a single result - the name of the current database. While the `SHOW DATABASES` (note the `S` at the end) returns a list of names, without the "Current" field.

[master < Task] PR
- [ ] Check, and update documentation if necessary
- [ ] Provide the full content or a guide for the final git message

To keep docs changelog up to date, one more thing to do:
- [ ] Write a release note here, including added/changed clauses
- [ ] Tag someone from docs team in the comments

2023-11-28 11:20 UTC, andrejtonev commented
@tonilastre this is something I wanted to introduce for a while. Didn't get a chance to do it sooner.
I know you are using the `SHOW DATABASES` query, I think this change should simplify the LABs flow.
P.S.
Not sure when this will get merged. Need to sync with @gitbuda and you about the timeline.

2023-12-04 15:18 UTC, gitbuda commented
NOTE: we should not merge this to v2.13 release because it's breaking on the Lab side, I'll tmp reject PR just to not merge it accidentally

2023-12-04 15:18 UTC, gitbuda requested changes
We just wait a bit

2023-12-04 15:32 UTC, andrejtonev commented
This will probably be merged into replication refactor part 7 and merged to master that way.

2024-01-10 11:36 UTC, andrejtonev commented
PR merged into #1550

2024-01-10 11:36 UTC, closed without merging