Fix index hints
memgraph/memgraph pull request #1606
Opened 2023-12-27 17:07 UTC by DavIvek

The issue is that even if the user gives a hint to memgraph's planner which index to use, memgraph will still generate multiple plans (with the user's hint included) and compare their costs based on its query cost estimator. 
To resolve the issue I added one more return value(from cost estimator) that tells us if the plan is generated by using index hints. Plans generated by using index hints will have bigger priority than ones that don't. 

[master < Epic] PR
- [ ] Check, and update documentation if necessary
- [ ] Write E2E tests
- [ ] Compare the [benchmarking results](https://bench-graph.memgraph.com/) between the master branch and the Epic branch
- [ ] Provide the full content or a guide for the final git message

[master < Task] PR
- [ ] Check, and update documentation if necessary
- [ ] Provide the full content or a guide for the final git message

To keep docs changelog up to date, one more thing to do:
- [ ] Write a release note here, including added/changed clauses
- [ ] Tag someone from docs team in the comments

closes #1592

2024-01-02 17:21 UTC, antepusic requested changes
Good work! Left a few comments for the sake of maintainability and thorough testing.

2024-01-02 17:21 UTC, antepusic commented on src/query/plan/planner.hpp
>    }
```
double cost = post_process.EstimatePlanCost(rewritten_plan, dba, symbol_table).first;
```
The `.first` in the above line is a bit arbitrary. I think the code will be more maintainable if `EstimatePlanCost` returned a struct. That way, you can take advantage of named fields.

2024-01-02 17:21 UTC, antepusic commented on tests/benchmark/query/planner.cpp
Can you add a test that shows Memgraph will use the hinted plan instead of the equal-cost plan that doesn’t use index hints?

2024-01-02 17:21 UTC, antepusic commented on tests/benchmark/query/planner.cpp
This PR means that there are two factors in plan selection: total cost and the presence of index hints. I think it would be a good idea to add a test showing that total cost takes precedence over index hinting, i.e. that Memgraph will prefer the less costly plan with no index hints over a more costly one with index hints.

2024-01-05 09:23 UTC, antepusic approved these changes
Thanks for addressing my comments! I think this is approvable now.

2024-01-10 08:04 UTC, Josipmrden requested changes

2024-01-10 08:15 UTC, Josipmrden commented
Please just alter the comments in planner.hpp to make the logic more readable

2024-01-11 08:50 UTC, Josipmrden approved these changes

2024-01-11 09:10 UTC, merged