Fix early exit for OR expression
memgraph/memgraph pull request #1738
Opened 2024-02-19 13:57 UTC by Josipmrden

Fix or expression not making an early exit if first branch is evaluated to true.

[master < Task] PR
- [ ] Check, and update documentation if necessary
- [ ] Provide the full content or a guide for the final git message

To keep docs changelog up to date, one more thing to do:
- [ ] Write a release note here, including added/changed clauses
- [ ] Tag someone from docs team in the comments

2024-02-21 12:38 UTC, as51340 requested changes

2024-02-21 12:38 UTC, as51340 commented on src/query/interpret/eval.hpp
> +      return value1 || value2;
if 
```suggestion
      if (value2.IsBool()) return value2;
      return false;
```

2024-02-21 12:38 UTC, as51340 commented on src/query/interpret/eval.hpp
> +      return value1 || value2;
if we came to this point, value1 is not bool or false so I think correct thing is just to return value2 ?

2024-02-23 11:22 UTC, as51340 approved these changes
:muscle:

2024-02-28 16:04 UTC, antoniofilipovic commented on src/query/interpret/eval.hpp
> +      // If first expression is true, don't evaluate the second one.
No need for comment

2024-02-28 16:04 UTC, antoniofilipovic approved these changes
LGTM, left comment tiny

2024-03-11 21:44 UTC, merged

2024-04-04 13:39 UTC, kgolubic commented
Release note entry:

> Added an early exit when doing `OR` filter expressions if the first expression evaluates to `true`.