Fetch edge by edge id
memgraph/memgraph pull request #1808
Opened 2024-03-11 18:43 UTC by gvolfing

Memgraph currently provides id based lookup for vertices, but lacks to ability to do the same for edge ids.
This PR is resolving that issue.

2024-03-19 08:20 UTC, antoniofilipovic requested changes
Just a few comments. This ended up as a nice solution :muscle:

2024-03-19 08:20 UTC, antoniofilipovic commented on src/query/plan/operator.cpp
> +    return std::vector<EdgeAccessor>{*maybe_edge};
What is the reason for returning `std::vector` here?

2024-03-19 08:20 UTC, antoniofilipovic commented on src/storage/v2/inmemory/storage.cpp
> +        return std::make_tuple(std::get<2>(out_edge), std::get<0>(out_edge), from_vertex, std::get<1>(out_edge));
You can use I think just std::tuple{...} because CTAD will kick in.

2024-03-19 12:02 UTC, Darych commented on tests/unit/storage_v2_durability_inmemory.cpp
> +      auto edge = acc->FindEdge(memgraph::storage::Gid::FromUint(0), memgraph::storage::View::OLD);
What is the purpose on iterating in loop without using `i` variable?

2024-03-19 12:02 UTC, Darych commented on tests/unit/storage_v2_durability_inmemory.cpp
> +    edge = acc->FindEdge(memgraph::storage::Gid::FromUint(kNumBaseEdges + 1), memgraph::storage::View::OLD);
Should we check also `auto edge = acc->FindEdge(memgraph::storage::Gid::FromUint(kNumBaseEdges), memgraph::storage::View::OLD);` for true?

2024-03-19 14:19 UTC, gvolfing commented on src/storage/v2/inmemory/storage.cpp
> +  using EdgeInfo = std::optional<std::tuple<EdgeRef, EdgeTypeId, Vertex *, Vertex *>>;
I would do that, if this part of the code would infect other parts, but this is not the case. I think it's fine to use a tuple in this case and not having to define a separate struct with the members just to have it used as a return type once. Please let me know if you want me to change it.

2024-03-19 14:57 UTC, gvolfing commented on src/storage/v2/edge_accessor.cpp
> +  if (!IsEdgeVisible(edge.ptr, transaction, view)) {
If a concurrent transaction tries to delete it. We will have to traverse the delta-chain of the Edge object to see if it is valid.

2024-03-19 16:56 UTC, Darych commented on src/storage/v2/inmemory/storage.cpp
> +  using EdgeInfo = std::optional<std::tuple<EdgeRef, EdgeTypeId, Vertex *, Vertex *>>;
No, makes sense. Let's keep it as it is.

2024-03-19 16:58 UTC, Darych commented on src/query/plan/operator.cpp
> +    if (value.IsDouble() && id != value.ValueDouble()) return std::nullopt;
I think the original idea of double was to increase range of supported integer numbers :)

2024-03-19 16:59 UTC, Darych approved these changes
LGTM

2024-03-27 11:38 UTC, merged

2024-04-07 08:57 UTC, kgolubic commented
@gvolfing can you please provide me with Release notes and related docs PR?