Control Delta allocation to be separate from storage
memgraph/memgraph pull request #1895
Opened 2024-04-02 12:55 UTC by Ignition

### Description

- Change PropertyValue's map from `std::map` -> `boost::container::flat_map`
- Template PropertyValue to take an allocator
- Custom delta container to ensure allocations exist separate to storage allocations

related to #1685

Using this benchmark
`FOREACH (i in range(1, 3000000) | CREATE (:Label1:Label2:Label3:Label4:Label5:Label6));`

RSS is now
```
IN_MEMORY_TRANSACTIONAL ~575MiB
IN_MEMORY_ANALYTICAL    ~560MiB
```

[master < Task] PR
- [x] Provide the full content or a guide for the final git message
    - **Explicit control over delta allocations**

### Documentation checklist
- [x] Add the documentation label tag
- [ ] Add the bug / feature label tag
- [x] Add the milestone for which this feature is intended
    - If not known, set for a later milestone
- [ ] Write a release note, including added/changed clauses
    - **[Release note text]**
- [ ] Link the documentation PR here
    - **[Documentation PR link]**
- [ ] Tag someone from docs team in the comments

2024-04-25 14:08 UTC, antoniofilipovic requested changes
Really great job, I don't have much comments but few suggestions

2024-04-30 12:31 UTC, Ignition commented on src/storage/v2/property_value.hpp
> +  using allocator_type = std::allocator_traits<Alloc>::template rebind_alloc<PropertyValueImpl>;
Old strange allocator design choice, type you are going to need to allocate for is a template parameter of the allocator. I require an allocator of the right type for the allocation to be correct.

2024-04-30 12:32 UTC, Ignition commented on src/storage/v2/property_value.hpp
> +  using list_t = std::vector<PropertyValueImpl, allocator_type>;
spoke about this before...its just because I wanted a smaller map, `boost::container::flat_map` is much smaller than `std::map`

2024-04-30 12:32 UTC, Ignition commented on src/storage/v2/property_value.hpp
> +    [[no_unique_address]] allocator_type alloc_;
Avoid the need to do empty base class optimization (EBO)

2024-04-30 14:46 UTC, antoniofilipovic approved these changes
Awesome job!

2024-06-19 13:26 UTC, kgolubic commented
@Ignition I'm missing the Release note entry.

2024-06-28 17:00 UTC, Ignition commented
This is being redone in different PR memgraph/memgraph#2151

2024-07-09 08:58 UTC, closed without merging