Count number of hops
memgraph/memgraph pull request #1935
Opened 2024-04-12 10:29 UTC by DavIvek

### Description
To be able to limit number of hops in query, firstly we need to count number of hops.

[master < Task] PR
- [ ] Provide the full content or a guide for the final git message
    - **[FINAL GIT MESSAGE]**

### Documentation checklist
- [ ] Add the documentation label tag
- [ ] Add the bug / feature label tag
- [ ] Add the milestone for which this feature is intended
    - If not known, set for a later milestone
- [ ] Write a release note, including added/changed clauses
    - **[Release note text]**
- [ ] Link the documentation PR here
    - **[Documentation PR link]**
- [ ] Tag someone from docs team in the comments

2024-04-19 05:38 UTC, gitbuda commented on src/query/interpret/frame.hpp
> +// Copyright 2024 Memgraph Ltd.
This should be reverted because nothing else changed in the file 👀

2024-04-19 05:39 UTC, gitbuda commented on src/query/plan/operator.cpp
> +    context.number_of_hops++;
I would also skip this for now, only "read" expansions for now 🤔

2024-04-19 05:41 UTC, gitbuda commented on src/query/plan/operator.cpp
> +    context.number_of_hops++;
But whatever we do here, it has to be document in the documentatio.

2024-04-19 05:45 UTC, gitbuda commented on src/query/plan/operator.cpp
> +    auto edges = std::move(edges_result.edges);
Redundant line, you can just `std::move(edges_result.edges)` two lines further, there are more cases like this in the current version of the code.

2024-04-19 05:47 UTC, gitbuda requested changes
@DavIvek A few minor fixes required, but overall looks good (this is the right size of a PR and the right first step 💪)

2024-05-03 13:25 UTC, Josipmrden reviewed
some comments but LGTM

2024-05-03 13:25 UTC, Josipmrden commented on src/query/context.hpp
> +#include <sys/types.h>
do you need this one?

2024-05-03 13:25 UTC, Josipmrden commented on src/query/interpreter.cpp
> +  spdlog::trace("Number of hops in the frame: {}", ctx_.number_of_hops);
i think this is a little bit aggressive. maybe to ommit this log

2024-05-03 13:25 UTC, Josipmrden commented on src/query/interpreter.cpp
> +  spdlog::trace("Number of hops in the frame: {}", ctx_.number_of_hops);
we already have it in the summary

2024-05-13 08:56 UTC, Josipmrden approved these changes

2024-05-13 10:32 UTC, gitbuda approved these changes
all comments resolved -> 🚀

2024-05-13 15:25 UTC, merged