`SHOW METRICS INFO` via query
memgraph/memgraph pull request #2052
Opened 2024-05-20 13:26 UTC by Josipmrden

### Description

Please briefly explain the changes you made here.

Please delete either the [master < EPIC] or [master < Task] part, depending on what are your needs.

[master < Epic] PR
- [ ] Write E2E tests
- [ ] Compare the [benchmarking results](https://bench-graph.memgraph.com/) between the master branch and the Epic branch
- [ ] Provide the full content or a guide for the final git message
    - [FINAL GIT MESSAGE]

[master < Task] PR
- [ ] Provide the full content or a guide for the final git message
    - **[FINAL GIT MESSAGE]**

### CI Testing Labels
Please select the appropriate CI test labels _(CI -build=**build-name** -test=**test-suite**)_

### Documentation checklist
- [ ] Add the documentation label tag
- [ ] Add the bug / feature label tag
- [ ] Add the milestone for which this feature is intended
    - If not known, set for a later milestone
- [ ] Write a release note, including added/changed clauses
    - **[Release note text]**
- [ ] Link the documentation PR here
    - **[Documentation PR link]**
- [ ] Tag someone from docs team in the comments

2024-06-04 18:05 UTC, antepusic approved these changes
Approving this in line with my previous comment

2024-06-04 18:41 UTC, as51340 requested changes
Nice work, have few comments, nothing too important :)

2024-06-04 18:41 UTC, as51340 commented on src/query/interpreter.cpp
> +        std::vector<std::vector<TypedValue>> results;
All this code is good, to make it better:
- info and metrics_info can be const
- use std::ranges::sort

2024-06-04 18:41 UTC, as51340 commented on src/storage/v2/storage.cpp
> +    result.emplace_back(memgraph::metrics::GetCounterName(i), memgraph::metrics::GetCounterType(i), "Counter",
Use some variable name for Counter instead of black magic

2024-06-04 18:41 UTC, as51340 commented on src/storage/v2/storage.cpp
> +                        memgraph::metrics::global_counters[i].load(std::memory_order_acquire));
no need to use memgraph::metrics, use just metrics::
and I think you don't need to use load, without load should suffice

2024-06-04 18:41 UTC, as51340 commented on src/storage/v2/storage.cpp
> +                        memgraph::metrics::global_gauges[i].load(std::memory_order_acquire));
Similar comments

2024-06-04 18:41 UTC, as51340 commented on src/storage/v2/storage.cpp
> +
use fmt::format

2024-06-04 18:41 UTC, as51340 commented on src/storage/v2/storage.cpp
> +      result.emplace_back(metric_name, memgraph::metrics::GetHistogramType(i), "Histogram", value);
std::move metric_name

2024-06-04 18:41 UTC, as51340 commented on src/storage/v2/storage.cpp
> +      result.emplace_back(metric_name, memgraph::metrics::GetHistogramType(i), "Histogram", value);
constant for histogram

2024-06-04 18:41 UTC, as51340 commented on src/storage/v2/storage.hpp
> +  virtual std::vector<EventInfo> GetMetrics() noexcept;
does it need to be virtual when both storage modes use same impl?

2024-06-04 18:42 UTC, as51340 commented
maybe in general, consider rebasing over master instead of merging master into branch, history is a bit cleaner then

2024-06-28 08:46 UTC, as51340 approved these changes
Few small changes required from the code side but you have approve

2024-06-28 08:46 UTC, as51340 commented on src/query/interpreter.cpp
> +    case DatabaseInfoQuery::InfoType::METRICS: {
use emplace_back everywhere in this method

2024-06-28 08:46 UTC, as51340 commented on src/query/interpreter.cpp
> +        std::ranges::sort(results.begin(), results.end(), [](const auto &record_1, const auto &record_2) {
```suggestion
        std::ranges::sort(results, [](const auto &record_1, const auto &record_2) {
```

2024-06-28 08:46 UTC, as51340 commented on src/query/interpreter.cpp
> +        std::ranges::sort(results.begin(), results.end(), [](const auto &record_1, const auto &record_2) {
your lambda comparator can be simpler:
```
auto const cmp = [](auto const &record1, auto const &record2) {
MG_ASSERT(record1[1].IsString()); // or some method similar to this exists
MG_ASSERT(record2[1].IsString()); // or some method similar to this exists

return record1[1].ValueString().compare(record2[1].ValueString());
```
};

2024-06-28 08:46 UTC, as51340 commented on src/storage/v2/disk/storage.cpp
> +  auto delta_size = transaction_.deltas.size();
define it closer to where you use it

2024-06-28 08:46 UTC, as51340 commented on src/storage/v2/inmemory/storage.cpp
> +    auto delta_size = deltas.size();
define it closer to where you use it.

2024-06-28 08:46 UTC, as51340 commented on src/storage/v2/inmemory/storage.cpp
> +      }
```suggestion
     auto const sum_func = [](uint32_t curr, auto const &gc_deltas) {
       return curr + gc_deltas.deltas_.size();
      }

      uint32_t total_delta_size = std::accumulate(unlinked_undo_buffers.begin(), unlinked_undo_buffers.end(), 0U, sum_func);
    
```
This should be correct, maybe I have some typo

2024-06-28 08:46 UTC, as51340 commented on src/storage/v2/mvcc.hpp
> +  memgraph::utils::OnScopeExit increment_unreleased_deltas(
You can here increment it without OnScopeExit, not sure what do you get?

2024-06-28 08:46 UTC, as51340 commented on src/storage/v2/storage.cpp
> +      auto metric_name = fmt::format("{0}_{1}p", std::string(name), std::to_string(percentile));
I think fmt can accept const char *, no need to convert it to string

2024-07-05 12:38 UTC, Josipmrden commented
Please delete either the [master < EPIC] or [master < Task] part, depending on what are your needs.

[master < Task] PR
- [X] Provide the full content or a guide for the final git message
    - **Added `SHOW METRICS INFO` query that exposes the system metrics via query**


### CI Testing Labels
Please select the appropriate CI test labels _(CI -build=**build-name** -test=**test-suite**)_


### Documentation checklist
- [X] Add the documentation label tag
- [X] Add the bug / feature label tag
- [X] Add the milestone for which this feature is intended
- [X] Write a release note, including added/changed clauses
    - **Added a new Enterprise query, `SHOW METRICS INFO`, that exposes the system metrics via query (same ones that are exposed through the HTTP monitoring endpoint at default port 9091)**
- [X] Link the documentation PR here
    - **https://github.com/memgraph/documentation/pull/809**
- [X] Tag someone from docs team in the comments @kgolubic

2024-07-11 10:16 UTC, merged

2024-07-18 09:50 UTC, kgolubic commented
For release note I'll use:

- Added a new query, `SHOW METRICS INFO`, which exposes the same metrics
available from the HTTP endpoint, now accessible via a query.
[#2052](https://github.com/memgraph/memgraph/pull/2052)