Add NuRaft logs
memgraph/memgraph pull request #2084
Opened 2024-05-31 11:47 UTC by as51340

### Description

Please briefly explain the changes you made here.

Please delete either the [master < EPIC] or [master < Task] part, depending on what are your needs.

[master < Epic] PR
- [ ] Write E2E tests
- [ ] Compare the [benchmarking results](https://bench-graph.memgraph.com/) between the master branch and the Epic branch
- [ ] Provide the full content or a guide for the final git message
    - [FINAL GIT MESSAGE]

[master < Task] PR
- [ ] Provide the full content or a guide for the final git message
    - **[FINAL GIT MESSAGE]**

### CI Testing Labels
Please select the appropriate CI test labels _(CI -build=**build-name** -test=**test-suite**)_

### Documentation checklist
- [ ] Add the documentation label tag
- [ ] Add the bug / feature label tag
- [ ] Add the milestone for which this feature is intended
    - If not known, set for a later milestone
- [ ] Write a release note, including added/changed clauses
    - **[Release note text]**
- [ ] Link the documentation PR here
    - **[Documentation PR link]**
- [ ] Tag someone from docs team in the comments

2024-06-03 08:25 UTC, Ignition requested changes

2024-06-03 08:25 UTC, Ignition commented on src/coordination/include/nuraft/logger.hpp
> +   *    Fatal:    1
use an enum

2024-06-03 13:44 UTC, Ignition approved these changes

2024-06-04 06:04 UTC, as51340 commented
@kgolubic RN: Added flag `--nuraft-log-file` for explicitly managing logs coming from NuRaft.

2024-06-04 08:43 UTC, antoniofilipovic approved these changes
Looks good to me

2024-06-04 11:48 UTC, merged

2024-06-06 07:37 UTC, kgolubic commented
This will be RN:

- A new flag, `--nuraft-log-file`, has been added to explicitly manage logs
  coming from NuRaft.
[#2084](https://github.com/memgraph/memgraph/pull/2084)