Fix issues on recovery of log store and state machine
memgraph/memgraph pull request #2241
Opened 2024-07-26 08:54 UTC by antoniofilipovic

This diff fixes the following bugs:
- assert on missing logs in the log store
- state machine not updating value on last committed index
- wrong recovery of a state machine after restart of coordinator. The state machine was recovered using all the logs in the log store, instead of using just once up to last_committed_idx from state machine

2024-07-26 08:54 UTC, antoniofilipovic commented
Git commit description, explain the changes you made here

---
__*Leave above in PR description, copy the below into a comment*__
___


### Tracking
- [ ] **[Link to Epic/Issue]**


### Standard development
- [ ] Update unit/E2E tests
- [ ] Compare the [benchmarking results](https://bench-graph.memgraph.com/) between the master branch this branch


### CI Testing Labels
- [ ] Select the appropriate CI test labels _(CI -build=**build-name** -test=**test-suite**)_


### Documentation checklist
- [ ] Add the documentation label
- [ ] Add the bug / feature label
- [ ] Add the milestone for which this feature is intended
    - If not known, set for a later milestone
- [ ] Write a release note, including added/changed clauses
    - **[ Release note text ]**
- [ ] **[ Documentation PR link memgraph/documentation#XXXX ]**
    - [ ] Is back linked to this development PR
- [ ] **[ Tag someone from docs team ]**

2024-08-06 08:18 UTC, as51340 requested changes
Good work, few questions

2024-08-06 09:44 UTC, antoniofilipovic commented on src/coordination/coordinator_log_store.cpp
> +    bool const is_entry_with_biggest_id = next_slot == GetNextSlot();
Here it can be true

2024-08-06 09:47 UTC, antoniofilipovic commented on src/coordination/coordinator_state_machine.cpp
> +    durability_->Put(kLastCommitedIdx, std::to_string(log_idx));
add mg_assert

2024-08-13 12:38 UTC, antoniofilipovic commented on src/coordination/coordinator_log_store.cpp
> +    return cs_new<log_entry>(0, buffer::alloc(sizeof(uint64_t)));
commented [here](https://github.com/memgraph/memgraph/pull/2241#discussion_r1715222802)

2024-08-13 12:40 UTC, antoniofilipovic commented on src/coordination/coordinator_log_store.cpp
> +  ret->reserve(end - start - 1);
Mistake, thanks for noticing

2024-08-13 12:56 UTC, antoniofilipovic commented on src/coordination/coordinator_state_machine.cpp
> +      if (!snapshot_ctx_str.has_value()) {
I was reading twice from disk, so this can be removed actually

2024-08-14 10:20 UTC, as51340 requested changes

2024-08-14 10:20 UTC, as51340 commented on src/coordination/coordinator_log_store.cpp
> +  ret->reserve(end - start - 1);
change this

2024-08-14 10:20 UTC, as51340 commented on src/coordination/coordinator_log_store.cpp
> +  entries.reserve(end - start - 1);
change needed

2024-08-14 21:02 UTC, antoniofilipovic commented on src/coordination/coordinator_log_store.cpp
> +  ret->reserve(end - start - 1);
somehow forgot, sorry. now it is fixed

2024-08-14 21:02 UTC, antoniofilipovic commented on src/coordination/coordinator_log_store.cpp
> +  entries.reserve(end - start - 1);
somehow forgot, changed now. thanks

2024-08-16 12:45 UTC, as51340 approved these changes

2024-08-16 19:33 UTC, merged