fix endpoint resolution
memgraph/memgraph pull request #2281
Opened 2024-08-14 12:08 UTC by antoniofilipovic

Endpoint resolution was an issue for failing the `coordinator.py` test. The problem is that we parsed both for ipv4 and ipv6, and `getaddrinfo` func could prefer ipv6 over ipv4, which would result in a problem when sending RPC message.

2024-08-14 12:08 UTC, antoniofilipovic commented
Git commit description, explain the changes you made here

---
__*Leave above in PR description, copy the below into a comment*__
___


### Tracking
- [ ] **[Link to Epic/Issue]**


### Standard development
- [ ] Update unit/E2E tests
- [ ] Compare the [benchmarking results](https://bench-graph.memgraph.com/) between the master branch this branch


### CI Testing Labels
- [ ] Select the appropriate CI test labels _(CI -build=**build-name** -test=**test-suite**)_


### Documentation checklist
- [ ] Add the documentation label
- [ ] Add the bug / feature label
- [ ] Add the milestone for which this feature is intended
    - If not known, set for a later milestone
- [ ] Write a release note, including added/changed clauses
    - **[ Release note text ]**
- [ ] **[ Documentation PR link memgraph/documentation#XXXX ]**
    - [ ] Is back linked to this development PR
- [ ] **[ Tag someone from docs team ]**

2024-08-15 09:25 UTC, Ignition requested changes
better solution is to make the server accept ipv6 + ipv4

Change server to be something like 
`auto serv_addr = sockaddr_in6{.sin6_family = AF_INET6, .sin6_port = htons(port), .sin6_addr = in6addr_any};`

2024-08-16 10:34 UTC, antoniofilipovic commented
> better solution is to make the server accept ipv6 + ipv4
> 
> Change server to be something like `auto serv_addr = sockaddr_in6{.sin6_family = AF_INET6, .sin6_port = htons(port), .sin6_addr = in6addr_any};`

As we synced on call, this needs more research as I am currently not sure if can we force the ipv4 address to map to ipv6 addresses on the server, and in that case will we disrupt anything on the server connections? 

I would rather go with the current deterministic resolution and revisit this later on

2024-08-16 12:46 UTC, Ignition approved these changes

2024-08-16 19:45 UTC, merged