Planner to replace point.distance filter with index scan
memgraph/memgraph pull request #2362
Opened 2024-10-01 15:28 UTC by Ignition

Make planner utilize spatial index when querying with point.distance function.

Example:
`WITH point({x:0,y:0}) AS a MATCH (m:L1) WHERE point.distance(m.prop, a) < 1 RETURN m;`

Currently the index is only utilized when the point its querying around (`a` in the query above) is an identifier (is extracted with WITH clause before). In one of the next PRs the planner will be changed to automatically extract constants to identifiers.

2024-10-01 15:28 UTC, Ignition commented
### Tracking
- [ ] **[Link to Epic/Issue]**


### Standard development
- [ ] Update unit/E2E tests
- [ ] Compare the [benchmarking results](https://bench-graph.memgraph.com/) between the master branch this branch


### CI Testing Labels
- [ ] Select the appropriate CI test labels _(CI -build=**build-name** -test=**test-suite**)_


### Documentation checklist
- [x] Add the documentation label
- [x] Add the bug / feature label
- [x] Add the milestone for which this feature is intended
    - If not known, set for a later milestone
- [ ] Write a release note, including added/changed clauses
    - **[ Release note text ]**
- [ ] **[ Documentation PR link memgraph/documentation#XXXX ]**
    - [ ] Is back linked to this development PR
- [ ] **[ Tag someone from docs team ]**

2024-10-28 10:54 UTC, Josipmrden requested changes
I think you're missing planner tests to test whether the correct plan and index was used. Please look at some of the e2e tests to augment this, in order for us to be sure that the index is being used and not ScanAll.

MATCH (n:L1 {prop1: POINT({x:1, y:1})}) RETURN n; 

seems not to be working

2024-10-28 15:18 UTC, Ignition commented
> MATCH (n:L1 {prop1: POINT({x:1, y:1})}) RETURN n;

@Josipmrden exact match is not part of this PR, but we did add `tests/e2e/query_planning/query_planning_point_index.py` to capture that `ScanAllByPointDistance` was being planned for.

2024-10-30 15:17 UTC, andrejtonev approved these changes

2024-10-31 07:28 UTC, as51340 approved these changes

2024-10-31 08:19 UTC, merged