Improve error messages
memgraph/memgraph pull request #2379
Opened 2024-10-06 12:10 UTC by gitbuda

The main motivation here is to significantly improve error messages so that they are much more useful in AI pipelines (e.g., based on insightful errors, an LLM can make multiple attempts to work with Memgraph).

2024-10-06 12:11 UTC, gitbuda commented
Antlr is a big part -> the upgrade to the latest version done under https://github.com/memgraph/memgraph/pull/2358

### Tracking
- [ ] **[Link to Epic/Issue]**

### Standard development
- [ ] Update unit/E2E tests
- [ ] Compare the [benchmarking results](https://bench-graph.memgraph.com/) between the master branch this branch

### CI Testing Labels
- [ ] Select the appropriate CI test labels _(CI -build=**build-name** -test=**test-suite**)_

### Documentation checklist
- [ ] Add the documentation label
- [ ] Add the bug / feature label
- [ ] Add the milestone for which this feature is intended
    - If not known, set for a later milestone
- [ ] Write a release note, including added/changed clauses
    - **[ Release note text ]**
- [ ] **[ Documentation PR link memgraph/documentation#XXXX ]**
    - [ ] Is back linked to this development PR
- [ ] **[ Tag someone from docs team ]**

2024-10-28 16:20 UTC, andrejtonev commented on src/query/frontend/opencypher/parser.hpp
> +        }
```suggestion
        try {
          if (exception) std::rethrow_exception(exception);
        } catch (const antlr4::NoViableAltException &ex) {
          error_ = "Error on line " + std::to_string(line) + " position " + std::to_string(position + 1) +
                   " with the " + token->getText() + " token. The underlying parsing error is " + message + "." +
                   " Take a look at clauses around and try to fix the query.";
        } catch (...) {
          error_ = "Error on line " + std::to_string(line) + " position " + std::to_string(position + 1) +
                   ". The underlying parsing error is " + message;
        }
```

2024-10-28 16:20 UTC, andrejtonev commented on src/query/frontend/stripped.cpp
> +      if (i + 1 <= original_.size()) {
```suggestion
      if (i < original_.size()) {
```

2024-10-28 16:20 UTC, andrejtonev commented on src/query/frontend/stripped.cpp
> +                              ". Remove that part of the query and try to rerun it.");
```suggestion
        throw LexingException(
            "Invalid query. There is a wrong token starting with {}. Remove that part of the query and try to rerun it.", original_[i]);
```

2024-10-28 16:20 UTC, andrejtonev commented on src/query/frontend/stripped.cpp
> +                              ". Remove that part of the query and try to rerun it.");
Should we add the position as well?

2024-11-25 08:39 UTC, katarinasupe requested changes

2024-11-25 08:39 UTC, katarinasupe commented on src/query/interpreter.cpp
> +              "User with username '{}' doesn't exist. A new user can be created via the CREAT USER query.", username);
```suggestion
              "User with username '{}' doesn't exist. A new user can be created via the CREATE USER query.", username);
```

2024-11-25 08:39 UTC, katarinasupe commented on src/query/interpreter.cpp
> +          "Query is part of an entreprise feature. In order to run it, you need an enterprise build and license.");
```suggestion
          "Query is part of the Enterprise feature. In order to run it, you need an Enterprise license.");
```

2024-11-25 08:39 UTC, katarinasupe commented on src/query/interpreter.cpp
> +      "Query is part of an entreprise feature. In order to run it, you need an enterprise build and license.");
```suggestion
      "Query is part of the Enterprise feature. In order to run it, you need an Enterprise license.");
```

2024-11-25 08:39 UTC, katarinasupe commented on src/query/interpreter.cpp
> +      "Query is part of an entreprise feature. In order to run it, you need an enterprise build and license.");
Fix all occurrences

2024-11-25 10:30 UTC, andrejtonev approved these changes

2024-11-25 21:21 UTC, gitbuda commented
This will be most likely part of 3.0

2025-02-06 16:00 UTC, andrejtonev commented
The full list of potential improvements can be found under
https://www.notion.so/memgraph/Review-and-improve-error-messages-99eea007219745c8ab9c7f7985b6f121

2025-02-09 19:26 UTC, merged