Dynamic relationship creation in Cypher
memgraph/memgraph pull request #2558
Opened 2024-12-18 11:15 UTC by Josipmrden

Added dynamic relationship creation in Cypher

2024-12-18 11:15 UTC, Josipmrden commented
### Tracking
- [ ] **[Link to Epic/Issue]**


### Standard development
- [ ] Update unit/E2E tests
- [ ] Compare the [benchmarking results](https://bench-graph.memgraph.com/) between the master branch this branch


### CI Testing Labels
- [ ] Select the appropriate CI test labels _(CI -build=**build-name** -test=**test-suite**)_


### Documentation checklist
- [ ] Add the documentation label
- [ ] Add the bug / feature label
- [ ] Add the milestone for which this feature is intended
    - If not known, set for a later milestone
- [ ] Write a release note, including added/changed clauses
    - **[ Release note text ]**
- [ ] **[ Documentation PR link memgraph/documentation#XXXX ]**
    - [ ] Is back linked to this development PR
- [ ] **[ Tag someone from docs team ]**

2024-12-31 10:53 UTC, gitbuda requested changes

2024-12-31 10:53 UTC, gitbuda commented on src/query/frontend/ast/cypher_main_visitor.cpp
> +      query_info_.is_cacheable = false;  // We can't cache queries with edge type parameters.
Add an additional comment explaining why we can't cache queries with edge type parameters?

2024-12-31 10:53 UTC, gitbuda commented on src/query/plan/operator.cpp
> +                     is_expansion_static ? dba_->EdgeTypeToName(*maybe_edge_type_id) : "<DYNAMIC>",
Why not unpack the whole expression and output something like `<DYNAMIC variable>`?

2024-12-31 10:53 UTC, gitbuda commented on src/query/plan/operator.cpp
> +storage::EdgeTypeId EvaluateEdgeType(const StorageEdgeType &edge_type, ExpressionEvaluator &evaluator,
Aha, one implication of this whole PR is users can more easily create a bunch of EdgeTypeIDs (I mean, it's not that hard even with the "static" EdgeType). Should we update documentation or put some kind of a limit on how many edge types is expected to be present in a given graph? 🤔

2024-12-31 10:53 UTC, gitbuda commented on src/query/frontend/ast/cypher_main_visitor.cpp
> +      types.emplace_back(expression);
What about caching of this? Because if the above is not cacheable, this one should also be not cacheable? 🤔

2024-12-31 10:53 UTC, gitbuda commented on src/query/plan/operator.cpp
> +storage::EdgeTypeId EvaluateEdgeType(const StorageEdgeType &edge_type, ExpressionEvaluator &evaluator,
Move this also to the PR description.

2024-12-31 10:53 UTC, gitbuda commented on src/query/plan/operator.cpp
> +                     is_expansion_static ? dba_->EdgeTypeToName(*maybe_edge_type_id) : "<DYNAMIC>",
2 options:
* if expression evaluation is not simple here, rewrite the string into `<DYNAMIC parameter|property_lookup>` (something more descriptive, but not huge)
* if expression evaluation is simple here -> add the exact name from the query

2024-12-31 10:53 UTC, gitbuda commented on src/query/plan/rule_based_planner.hpp
> +            "happen!");
`"Failed to work with dynamic edge types! Avoid using parameters or variables when creating a new edge. Also, please contact Memgraph support, as this scenario should not happen (this is an unexpected code path, but we didn't want to just crash Memgraph, help us improve the query planner)!"`

@Ana-Marija-design this is an interesting error message to craft 😃

2025-02-10 13:21 UTC, Josipmrden commented on src/query/frontend/ast/cypher_main_visitor.cpp
> +      query_info_.is_cacheable = false;  // We can't cache queries with edge type parameters.
@DavIvek can you please guide me through this one, why we can't cache, I copied from node dynamic creation

2025-02-10 15:30 UTC, DavIvek commented on src/query/frontend/ast/cypher_main_visitor.cpp
> +      query_info_.is_cacheable = false;  // We can't cache queries with edge type parameters.
Queries with edge types and node labels set as parameters shouldn't be cached because these parameters are resolved during the parsing stage. The same parameter could be resolved to different values if the user changes its value.

2025-02-10 15:36 UTC, DavIvek commented on src/query/frontend/ast/cypher_main_visitor.cpp
> +      types.emplace_back(expression);
These queries can be cached because expressions are not evaluated during the parsing stage. Queries with dynamic relationship types and labels can be cached, but their plans shouldn't be once support for dynamic relationship types and labels is added to the `MERGE` and `MATCH` clauses. In that case, the planner wouldn't be able to select the correct plan for these queries since expression evaluation happens in a later phase. However, since this feature is not currently supported in `MERGE` and `MATCH`, it's not an issue, and these queries can still be cached.

Related issue: https://github.com/memgraph/memgraph/issues/1848

2025-02-12 13:20 UTC, Josipmrden commented on src/query/plan/operator.cpp
> +                     is_expansion_static ? dba_->EdgeTypeToName(*maybe_edge_type_id) : "<DYNAMIC>",
out of scope for this PR, approved by @colinbarry

2025-02-12 13:20 UTC, Josipmrden commented on src/query/plan/operator.cpp
> +                     is_expansion_static ? dba_->EdgeTypeToName(*maybe_edge_type_id) : "<DYNAMIC>",
we don't have the `ExpressionEvaluator` at this point so unable to do more fine grained outputs.

2025-02-12 13:22 UTC, Josipmrden commented on src/query/plan/operator.cpp
> +storage::EdgeTypeId EvaluateEdgeType(const StorageEdgeType &edge_type, ExpressionEvaluator &evaluator,
In the PR description. I wouldn't add any limit, let the users use it, I don't think they'll go over it (same with dynamic node creation that we already have).

2025-02-13 11:10 UTC, colinbarry commented on src/query/frontend/ast/ast.hpp
> +      }
Something to consider: using `std::visit` rather than `get_if`. That way, if we expand expand the variant's alternatives, we'll get compile-time errors.

```cpp
std::visit([&](auto &&arg) -> QueryEdgeType {
    using T = std::decay_t<decltype(arg)>;
    if constexpr (std::is_same_v<T, EdgeTypeIx>) {
      return storage->GetEdgeTypeIx(arg.name);
    } else if constexpr (std::is_same_v<T, Expression *>) {
      return arg->Clone(storage);
    }
  }, edge);
```

2025-02-14 10:00 UTC, Ignition commented on src/query/frontend/ast/ast.hpp
> +      }
or 
```
auto const do_thing = Overloaded{
  [&](EdgeTypeIx const &) { ... },
  [&](Expression const *) { ... },
};
std::visit(do_thing, edge);
```

2025-02-16 11:03 UTC, gitbuda approved these changes

2025-02-16 14:42 UTC, merged