[master < T0774-MG] Update stats with query modules
memgraph/memgraph pull request #304
Opened 2021-11-24 15:33 UTC by antonio2368

[master < Task] PR
- [ ] Check, and update documentation if necessary
- [ ] Update [changelog](https://docs.memgraph.com/memgraph/changelog)

2021-11-25 09:55 UTC, jbajic approved these changes

2021-11-25 11:52 UTC, antaljanosbenjamin requested changes

2021-11-25 11:52 UTC, antaljanosbenjamin commented on src/query/procedure/mg_procedure_impl.cpp
> +    ctx->execution_stats[query::ExecutionStats::Key::DELETED_EDGES] += (*result)->second.size();
At this point `result` can be `std::nullopt`, therefore I would push this after the following `if` statement after which `result` holds a valid value.

2021-11-25 11:52 UTC, antaljanosbenjamin commented on src/query/procedure/mg_procedure_impl.cpp
> +    ctx->execution_stats[query::ExecutionStats::Key::DELETED_NODES] += 1;
I would put this into the inner body of the following `if` statement, because result can be `std::nullopt` here, which means no deletion.

2021-11-25 11:52 UTC, antaljanosbenjamin commented on src/query/procedure/mg_procedure_impl.cpp
> +    ctx->execution_stats[query::ExecutionStats::Key::DELETED_EDGES] += 1;
Same as for `delete_vertex`.

2021-11-25 12:04 UTC, kostasrim approved these changes

2021-11-25 12:05 UTC, kostasrim commented
I think once @antaljanosbenjamin comments are addressed this should be good to merge

2021-11-26 14:19 UTC, antaljanosbenjamin approved these changes

2021-11-26 14:31 UTC, merged