[master < T0847-MG] Update precommit hooks
memgraph/memgraph pull request #393
Opened 2022-05-06 11:04 UTC by jbajic

This PR introduces new commit hooks:
- `black` formatter for python files,
- Trailing space check,
- Newline check.

and it updates how we run the `clang-format` hook with the automated pre-commit repository.

[master < Task] PR
- [x] ~~Check, and update documentation if necessary~~
- [x] ~~Update [changelog](https://docs.memgraph.com/memgraph/changelog)~~

2022-05-10 09:02 UTC, antaljanosbenjamin approved these changes
I like the inclusion of `pre-commit`, I think it really improves our pre-commit hooks!

2022-05-10 09:02 UTC, antaljanosbenjamin requested changes
I wanted to request changes because of modifying `init.sh`, but accidentally approved.

2022-05-10 09:11 UTC, jbajic commented on .pre-commit-config.yaml
> +  - repo: https://github.com/pre-commit/pre-commit-hooks
You are right, will do that

2022-05-11 10:09 UTC, antaljanosbenjamin approved these changes

2022-05-11 19:07 UTC, merged