Correcting USE_JEMALLOC flag
memgraph/memgraph pull request #401
Opened 2022-05-25 20:32 UTC by 42jeremy

[master < Task] PR
- [ ] Check, and update documentation if necessary
- [ ] Update [changelog](https://docs.memgraph.com/memgraph/changelog)

2022-05-26 12:21 UTC, antaljanosbenjamin requested changes
Could you please also remove `jemalloc` from the libs folder? You probably have to remove the references to jemalloc from `libs/setup.sh` and it should be okay.

@jbajic I think if this will be done, than we can also remove the cache for jemalloc.

2022-05-27 06:24 UTC, antaljanosbenjamin commented on libs/.gitignore
> -!jemalloc.cmake
Wow, really nice!

2022-05-27 06:24 UTC, antaljanosbenjamin approved these changes
LGTM!

2022-05-30 12:23 UTC, kostasrim approved these changes

2022-06-07 12:55 UTC, jbajic approved these changes

2022-06-09 16:55 UTC, merged