T0889 mg throw exceptions when null is used in the simple form of case clause v2
memgraph/memgraph pull request #432
Opened 2022-07-05 15:13 UTC by gvolfing

[master < Task] PR
- [ ] Check, and update documentation if necessary
- [ ] Update [changelog](https://docs.memgraph.com/memgraph/changelog)

2022-07-05 15:22 UTC, gvolfing commented
Replacement PR for https://github.com/memgraph/memgraph/pull/422

2022-07-06 07:50 UTC, antaljanosbenjamin requested changes

2022-07-06 07:50 UTC, antaljanosbenjamin commented on tests/gql_behave/tests/memgraph_V1/features/case.feature
> +            |  'something went wrong'                                                                      |
```suggestion
            WITH 2 AS name RETURN CASE name WHEN 3 THEN 'something went wrong' WHEN null THEN "doesn't work" ELSE 'works' END
            """
        Then the result should be:
            |  CASE name WHEN 3 THEN 'something went wrong' WHEN null THEN "doesn't work" ELSE 'works' END |
            |  'works'                                                                      |
```

Seeing the expected output it is a bit confusing to see `something went wrong` as expected result, that's why I proposed these changes.

2022-07-06 07:50 UTC, antaljanosbenjamin commented on tests/gql_behave/tests/memgraph_V1/features/case.feature
> +            |  'works'                                                                                               |
I was thinking about adding a test case where the test expression itself is `null`. So `WITH null AS name RETURN CASE name WHEN null THEN "doesn't work" WHEN 2 "doesn't work" ELSE 'works' END`.

2022-07-07 11:16 UTC, antaljanosbenjamin approved these changes

2022-07-07 20:53 UTC, jbajic approved these changes

2022-07-11 06:09 UTC, antaljanosbenjamin commented
[Docs PR](https://github.com/memgraph/docs/pull/461)

2022-07-11 13:00 UTC, merged