[project-pineapples < T0951-MG] Create query engine v2
memgraph/memgraph pull request #444
Opened 2022-07-11 09:28 UTC by jbajic

[project-pineapples < T0951-MG] PR
- [ ] Check, and update documentation if necessary
- [ ] Update [changelog](https://docs.memgraph.com/memgraph/changelog)

2022-07-13 15:00 UTC, antaljanosbenjamin commented on src/query/v2/CMakeLists.txt
> +define_add_lcp(add_lcp_query lcp_query_2_cpp_files generated_lcp_query_2_files)
Can this be `lcp_query_v2`? Just to be consistent how the lcp related things are handled in storage v2/v3.

2022-07-13 15:03 UTC, antaljanosbenjamin commented on src/query/v2/CMakeLists.txt
> +define_add_lcp(add_lcp_query lcp_query_2_cpp_files generated_lcp_query_2_files)
And I just noticed I also didn't update this properly in storage-v3! Note for myself.

2022-07-13 15:08 UTC, antaljanosbenjamin commented on src/query/v2/CMakeLists.txt
> +target_link_libraries(mg-query-v2 antlr_opencypher_parser_lib_2)
Also, can this be v2?

2022-07-13 15:11 UTC, antaljanosbenjamin requested changes
I messed up the review, but my comments can be read above. Sorry for this.

2022-07-13 15:22 UTC, jbajic commented on .github/workflows/release_centos8.yaml
> +          cmake ..sas
Wow I did not notice this

2022-07-19 10:22 UTC, antaljanosbenjamin approved these changes
Because the code is just copied, we are merging this without eliminating all of the clang-tidy warnings.

2022-07-19 10:28 UTC, merged