Fix RETURN true, false query
memgraph/memgraph pull request #502
Opened 2022-08-13 10:39 UTC by gitbuda

[master < Task] PR
- [ ] Update [changelog](https://docs.memgraph.com/memgraph/changelog)
- [ ] Provide the full content or a guide for the final git message -> `Fix RETURN true, false query`

Fixes #470

2022-08-15 06:29 UTC, 42jeremy commented
Is the workflow common/important enough so we want a e2e test to cover it?

2022-08-15 06:29 UTC, 42jeremy approved these changes

2022-08-15 06:29 UTC, 42jeremy reviewed
@gitbuda Is the workflow common/important enough so we want a e2e test to cover it?

2022-08-16 10:02 UTC, jbajic requested changes
This is a specific solution to a more general problem. The issue is that we replace all returns of constant expressions with default values, `true`, `0`, `0.0`, and this solves only the bool part, but e.g. `RETURN 1,2;` and `RETURN 0.1, 0.2;` still fails. I would close this issue when all of the cases are covered.

2022-08-16 16:39 UTC, gitbuda commented
> This is a specific solution to a more general problem. The issue is that we replace all returns of constant expressions with default values, `true`, `0`, `0.0`, and this solves only the bool part, but e.g. `RETURN 1,2;` and `RETURN 0.1, 0.2;` still fails. I would close this issue when all of the cases are covered.

You're right and good catch! I would explore a bit more to find more details on what actually has to be done and then decide, stay tuned... + moving this PR to the Draft stage

2023-06-16 23:57 UTC, gitbuda commented
Closing this in the end, because the solution is not full + it's easy to write an alternative query that will work (using aliases).

2023-06-16 23:57 UTC, closed without merging