[project-pinapples < T1010] Implement query engine client
memgraph/memgraph pull request #531
Opened 2022-09-02 13:52 UTC by kostasrim

[master < Epic] PR
- [ ] Check, and update documentation if necessary
- [ ] Update [changelog](https://docs.memgraph.com/memgraph/changelog)
- [ ] Write E2E tests
- [ ] Compare the [benchmarking results](https://bench-graph.memgraph.com/) between the master branch and the Epic branch
- [ ] Provide the full content or a guide for the final git message

[master < Task] PR
- [ ] Check, and update documentation if necessary
- [ ] Update [changelog](https://docs.memgraph.com/memgraph/changelog)
- [ ] Provide the full content or a guide for the final git message

2022-09-11 15:38 UTC, gitbuda commented on src/query/v2/shard_request_manager.hpp
> +struct ExecutionState {
Add in the comment what's the point with the state? Is `ExecutionState` part of `ExecutionContext` while `ShardRequestManager` is part of `InterpreterContext`?

2022-09-11 15:40 UTC, gitbuda commented on src/query/v2/shard_request_manager.hpp
> +  ShardRequestManager(CoordinatorClient coord, memgraph::io::Io<TTransport> &&io)
Since `coord` is also moved, should it also be `&&`?

2022-09-12 07:40 UTC, gitbuda commented on src/query/v2/shard_request_manager.hpp
> +class ShardRequestManager : public ShardRequestManagerInterface {
One per query!

2022-09-12 07:41 UTC, gitbuda commented on src/query/v2/shard_request_manager.hpp
> +class ShardRequestManagerInterface {
unique ptr inside the ExecutionContext

2022-09-12 07:43 UTC, gitbuda commented on src/query/v2/shard_request_manager.hpp
> +struct ExecutionState {
The state object should be created per cursor, e.g. `ScanAll` will have the state

2022-09-21 13:26 UTC, spacejam commented on src/coordinator/shard_map.hpp
> +    const auto id = labels.find(name)->second;
```suggestion
    const auto id = labels.at(name);
```

2022-09-21 13:28 UTC, spacejam commented on src/coordinator/shard_map.hpp
> +  auto FindShardToInsert(const LabelName &name, CompoundKey &key) {
you can use `GetShardForKey` instead of this method

2022-09-21 13:29 UTC, spacejam commented on src/coordinator/shard_map.hpp
> +    const auto id = labels[label];
```suggestion
    const auto id = labels.at(label);
```

2022-09-21 14:07 UTC, spacejam requested changes
just the few code suggestions / single double-check thing

2022-09-21 15:00 UTC, 42jeremy requested changes

2022-09-21 15:13 UTC, kostasrim commented on src/query/v2/plan/operator.cpp
> +        ResetExecutionState();
all good

2022-09-21 15:13 UTC, 42jeremy approved these changes

2022-09-21 16:38 UTC, spacejam approved these changes

2022-09-22 13:05 UTC, merged