[E118-MG < T0999-MG] Implement expression evaluator in storage v3
memgraph/memgraph pull request #534
Opened 2022-09-06 10:59 UTC by jbajic

[master < Task] PR
- [ ] Check, and update documentation if necessary
- [ ] Update [changelog](https://docs.memgraph.com/memgraph/changelog)
- [ ] Provide the full content or a guide for the final git message

2022-09-15 21:01 UTC, jbajic commented on src/storage/v3/delta.hpp
> +        // std::destroy_at(&vertex_edge.vertex_id);
Discuss this

2022-09-21 06:59 UTC, antaljanosbenjamin commented on .clang-tidy
> +         -bugprone-macro-parentheses'
I think is a merge went wrong.

2022-09-21 12:05 UTC, antaljanosbenjamin requested changes

2022-09-21 12:05 UTC, antaljanosbenjamin commented on src/storage/v3/name_id_mapper.hpp
> +  std::unordered_map<uint64_t, std::string> id_to_name_;
I think we have to introduce another map to store the mapping in the name -> id direction to avoid linear lookups.

2022-09-21 12:05 UTC, antaljanosbenjamin commented on src/storage/v3/vertex_accessor.cpp
> +#include "typed_value.hpp"
Either remove or provide the correct path.

2022-09-21 13:19 UTC, 42jeremy approved these changes

2022-09-21 15:26 UTC, merged