[E129-MG < T1030-MG] Tech debts
memgraph/memgraph pull request #540
Opened 2022-09-08 17:03 UTC by BorisTasevski

2022-09-09 14:08 UTC, Josipmrden approved these changes

2022-09-09 16:41 UTC, gitbuda requested changes

2022-09-09 16:41 UTC, gitbuda commented on src/glue/auth_checker.hpp
> +  const memgraph::query::DbAccessor &dba_;
Replace `const &` with `const *` because it's more clear that you are holding a pointer

2022-09-13 08:52 UTC, gitbuda approved these changes
Seems good!

2022-09-13 09:37 UTC, merged