[project-pineapples <] Remove redundant ShardMap copy from MachineManager to avoid race conditions
memgraph/memgraph pull request #631
Opened 2022-10-31 16:50 UTC by spacejam

[master < Epic] PR
- [ ] Check, and update documentation if necessary
- [ ] Update [changelog](https://docs.memgraph.com/memgraph/changelog)
- [ ] Write E2E tests
- [ ] Compare the [benchmarking results](https://bench-graph.memgraph.com/) between the master branch and the Epic branch
- [ ] Provide the full content or a guide for the final git message

[master < Task] PR
- [ ] Check, and update documentation if necessary
- [ ] Update [changelog](https://docs.memgraph.com/memgraph/changelog)
- [ ] Provide the full content or a guide for the final git message

2022-10-31 17:47 UTC, jbajic approved these changes
Commenting on my own code :smile: , looks good to me!

2022-10-31 17:47 UTC, jbajic commented on src/coordinator/shard_map.cpp
> +      id_to_names.insert({id.AsUint(), name});
```suggestion
      id_to_names.emplace(id.AsUint(), name);
```

2022-11-01 10:47 UTC, antaljanosbenjamin requested changes

2022-11-01 15:28 UTC, antaljanosbenjamin approved these changes

2022-11-01 17:33 UTC, merged