[< T298-MAGE] allShortest bugfix
memgraph/memgraph pull request #636
Opened 2022-11-02 23:04 UTC by brunos252

[master < Epic] PR
- [ ] Check, and update documentation if necessary
- [ ] Update [changelog](https://docs.memgraph.com/memgraph/changelog)
- [ ] Write E2E tests
- [ ] Compare the [benchmarking results](https://bench-graph.memgraph.com/) between the master branch and the Epic branch
- [ ] Provide the full content or a guide for the final git message

[master < Task] PR
- [ ] Check, and update documentation if necessary
- [ ] Update [changelog](https://docs.memgraph.com/memgraph/changelog)
- [ ] Provide the full content or a guide for the final git message

2022-11-03 09:52 UTC, antaljanosbenjamin requested changes
Could you please also add a test? Check `tests/unit/interpreter.cpp` to get to know how you can create unit tests easily.

2022-11-03 09:52 UTC, antaljanosbenjamin commented on src/query/plan/operator.cpp
> +          if ((node != TypedValue(next_vertex, pull_memory)).ValueBool()) continue;
It is a slight change, but you can avoid constructing a `TypedValue` by:
```suggestion
          const auto &node = frame[self_.common_.node_symbol];
          ExpectType(self_.common_.node_symbol, existing_node, TypedValue::Type::Vertex);
          if (node.ValueVertex() != next_vertex) continue;
```
Unless I am missing something, in that case please let me know. Also, please format the code before committing, I made the changes on github, so the formatting might be slightly off.

2022-11-03 09:52 UTC, antaljanosbenjamin commented on src/query/plan/operator.cpp
> +          if ((node != TypedValue(next_vertex, pull_memory)).ValueBool()) continue;
And if my solution works, then please also remove the `pull_memory` variable.

2022-11-03 14:10 UTC, jbajic approved these changes

2022-11-04 13:01 UTC, kostasrim approved these changes

2022-11-04 15:17 UTC, antaljanosbenjamin approved these changes

2022-11-04 18:36 UTC, merged