Add notification warning when commit to replica fails
memgraph/memgraph pull request #792
Opened 2023-02-19 14:24 UTC by Josipmrden

Up to now, an exception would be thrown if there was a write query on MAIN instance with at least one replica down. It's now upgraded to only show notification that main has committed data but not synced with all replicas.

[master < Task] PR
- [X] Check, and update documentation if necessary
- [ ] Provide the full content or a guide for the final git message

To keep docs changelog up to date, one more thing to do:
- [X] Write a release note here
- [X] Tag someone from docs team in the comments

Release note: [Replication] When committing new changes on MAIN instance, a notification is displayed instead of exception if data has not been synced with all replicas (e.g. in case a replica is down).

2023-02-19 14:24 UTC, Josipmrden commented
@vpavicic tagging for release note

2023-02-20 09:23 UTC, vpavicic commented
@Josipmrden Like this?

From this release, when changes are commited on MAIN instance but cannot be synced with all REPLICA instances (for example, a replica is unavailable), a notification is displayed instead of an exepction.

2023-02-21 16:15 UTC, Josipmrden commented
> @Josipmrden Like this?
> 
> From this release, when changes are commited on MAIN instance but cannot be synced with all REPLICA instances (for example, a replica is unavailable), a notification is displayed instead of an exepction.

Yes, I like this one

2023-02-28 10:59 UTC, gitbuda commented on src/query/interpreter.cpp
> +                               "At least one SYNC replica has not confirmed committing last transaction.");
All this is possible as a part of the constructor line.

2023-02-28 10:59 UTC, gitbuda commented on src/query/interpreter.cpp
> +                               "At least one SYNC replica has not confirmed committing last transaction.");
Expand the notification with the part in which you are trying to suggest user what it should be done.

2023-02-28 11:01 UTC, gitbuda requested changes
Some minor suggestions in the inline comments.

2023-06-20 09:41 UTC, antoniofilipovic commented
@Josipmrden what is status with this PR

2023-06-20 09:42 UTC, Josipmrden commented
> @Josipmrden what is status with this PR

I'll convert this to Draft and we push it to v2.10

2023-08-04 09:09 UTC, andrejtonev commented
@Josipmrden should this be merged?

2023-10-19 12:36 UTC, closed without merging