[master < T606-FL] Fix AllShortest multiple edges between nodes
memgraph/memgraph pull request #832
Opened 2023-03-16 18:01 UTC by brunos252

[master < Task] PR
- [ ] Check, and update documentation if necessary
- [ ] Provide the full content or a guide for the final git message

To keep docs changelog up to date, one more thing to do:
- [ ] Write a release note here
- [ ] Tag someone from docs team in the comments

2023-03-16 18:03 UTC, brunos252 commented
`total_cost_` could be renamed. Also, `visited_cost_` might not be necessary anymore

2023-03-16 18:05 UTC, Josipmrden requested changes

2023-03-16 18:05 UTC, Josipmrden commented on tests/gql_behave/tests/memgraph_V1/features/memgraph_allshortest.feature
> +            | 1 |
This is not a good test since we don't know what's the cost of the shortest path

2023-03-16 18:05 UTC, Josipmrden commented on src/query/plan/operator.cpp
please make methods out of this pull, it's really hard to debug without having this logic hierarchically separated

2023-03-23 10:16 UTC, Josipmrden approved these changes

2023-03-23 10:16 UTC, Josipmrden commented
Approved

2023-03-28 15:02 UTC, antoniofilipovic commented on src/query/plan/operator.cpp
> +    };
```suggestion
    auto create_state = [upper_bound_set = upper_bound_set_](const VertexAccessor &vertex, int64_t depth) {
      return std::make_pair(vertex, upper_bound_set ? depth : 0);
    };
```

This way, you don't need to capture everything

2023-03-28 15:05 UTC, antoniofilipovic approved these changes
I made one suggestin, otherwise, I didn't check code in full depth, feel free to use suggestion if you like

2023-03-29 14:39 UTC, merged